# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
