# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmark', '0003_bookmark_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='published_date',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
