# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=django.utils.timezone.now, unique=True, verbose_name='url'),
            preserve_default=False,
        ),
    ]
